           var opsvisibleColumnIndexes = [0];
            var opscolors = [];
            for (var i = 1; i < opscolumns.length; i++) {
                if (opscolumns[i].visible) {
                    opscolors.push(opscolumns[i].color);
                    opsvisibleColumnIndexes.push(i);
                } else {
                    opscolors.push(opscolumns[i].disabledColor);
                    opsvisibleColumnIndexes.push({
                        calc: nullFunc,
                        type: opscolumns[i].type,
                        label: opscolumns[i].label,
                    });
                }
            };
            opsdataView.setColumns(opsvisibleColumnIndexes);
            opschart.draw(opsdataView, {
                colors: opscolors,
                interpolateNulls: true,
                width: 1800,
                height: 500,
                tooltip: { isHtml: true, textStyle: { fontSize: 10 } },       
                legend: {
                    position: 'right',
                    maxlines: 1,
                    textStyle: {
                        fontSize: 10
                    }
                },
                chartArea: {
                    'width': '80%',
                    'height': '80%'
                },
                hAxis: {
                    textPosition: 'none'
                },
                vAxis: {
                    textStyle: {
                        fontSize: 8
                    },
                    title: 'Transactions'
                }
            });
            var etimesvisibleColumnIndexes = [0];
            var etimescolors = [];
            for (var i = 1; i < etimescolumns.length; i++) {
                if (etimescolumns[i].visible) {
                    etimescolors.push(etimescolumns[i].color);
                    etimesvisibleColumnIndexes.push(i);
                } else {
                    etimescolors.push(etimescolumns[i].disabledColor);
                    etimesvisibleColumnIndexes.push({
                        calc: nullFunc,
                        type: etimescolumns[i].type,
                        label: etimescolumns[i].label,
                    });
                }
            };
            etimesdataView.setColumns(etimesvisibleColumnIndexes);
            etimeschart.draw(etimesdataView, {
                colors: etimescolors,
                interpolateNulls: true,
                width: 1800,
                height: 500,
                tooltip: { isHtml: true, textStyle: { fontSize: 10 } },       
                legend: {
                    position: 'none',
                    textStyle: {
                        fontSize: 8
                    }
                },
                chartArea: {
                    'width': '80%',
                    'height': '80%'
                },
                hAxis: {
                    title: 'Time',
                    slantedText: true,
                    slantedTextAngle: 45,
                    textStyle: {
                        fontSize: 8
                    }
                },
                vAxis: {
                    textStyle: {
                        fontSize: 8
                    },
                    title: 'Average elapsedTime'
                }
            });
        };
    </script>
</head>
<body>
    <div id="opschart"></div>
    <div id="etimeschart"></div>
